### ISSUE TITLE
Initial library creation tasks

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy-financial#2]
This is a  rough "to do" list. The tasks probably need to be refined.

- [x] Get the financial functions from numpy into this repo., and create a basic package structure (setup.py, etc) that allows the package to be installed locally.
        - *Done in https://github.com/numpy/numpy-financial/pull/1*
- [x] Configure testing for running tests with pytest, and set up CI.
       - *I set up a github workflow to run the tests with numpy >= 1.17 with Python versions 3.5, 3.6, 3.7 on ubuntu.  That's enough to consider this task done.  We can add more platforms later.*
- [x] Change `setup.py` and anything else necessary so the version is visible wherever it is needed: in `setup.py`, as `numpy_financial.__version__`, etc.
      - *Done in* https://github.com/numpy/numpy-financial/commit/bf4808cae12204e9c6661a8be967c713e15ca9a4
- [x] Set up documentation (Sphinx, etc.)
      - *Documentation builds on each push to the master branch, and is available to view at* https://numpy.org/numpy-financial/
- [x] Upload package to PyPI; get feedback.
      - *Version 0.1.0 was uploaded to PyPI on October 10, 2019.*
- [x] Release 1.0

After releasing 1.0, we can:
* Add deprecation warnings to the financial functions in NumPy.
* Transfer the open GitHub issues about the financial functions from the NumPy repo to this one.
* Freeze the NumPy financial library.  Direct all future issues and pull requests to this repo.

**Comment by person142** [comment]
@WarrenWeckesser given that 1.0 has been released, it looks like everything in this issue has been done?

**Comment by WarrenWeckesser** [comment]
@person142, yes, thanks for the reminder!
