### ISSUE TITLE
Wrong IRR calculated (discrepency from Excel) 

### ISSUE THREAD

**Issue by herbzhao** [numpy/numpy-financial#28]
### Reproducing code example:
```
import numpy as np

a = np.array([-50, -100, 600, 300, -100])
print(np.irr(a))
```

This will yield a negative result (-76%), while the actual IRR should be 185%.

**Comment by seberg** [comment]
I am very sure that these are simply different conventions, so that at best it could be nice to make the documentation more clear if it is not (Help with that is always appreciated).

Note that I moved the function to `numpy-financial` the financial functions are deprecated within numpy itself, and we do not plan to update them there, users should use `numpy-finanvial` instead (or find a different alternative).

**Comment by Kai-Striega** [comment]
The IRR is the rate required for a series of cash flows to have a net present value of  0.

To find the IRR for a series of ``n`` cash flows this is equivalent to solving the following equation:

    0 = C_0 + C_1 / ((1+IRR) ^ 1) + .... + C_n / ((1+IRR)^n

But this can have multiple solutions which, in this case, include both 185% and -76%. By default, NumPy returns the rate closest to zero. This does not seem to be the case in Excel.

As a side note, you can also get the -76% in Excel by using the ``guess`` argument. So if you have your cash flows in the range C2:G2 you can enter ``=IRR(C2:G2, -75%)`` which will return the same result as NumPy.

**Comment by bryantsa08** [comment]
Kai - I ran into the same problem described in this issue. For some cash flows, this irr function returns the root that is not useful. 

I created a pull request that adds the ability to have an initial guess, which resolves this issue. It is a simple change to the code. Please let me know if you need any additional tests as it would be nice to have this implemented in the package.

**Comment by moijn001** [comment]
> Kai - I ran into the same problem described in this issue. For some cash flows, this irr function returns the root that is not useful.
> 
> I created a pull request that adds the ability to have an initial guess, which resolves this issue. It is a simple change to the code. Please let me know if you need any additional tests as it would be nice to have this implemented in the package.

Did this functionality make it to a version of Numpy Financial?  Would be a great addition to have.
