### ISSUE TITLE
IRR chooses solution closest to zero not always correct choice

### ISSUE THREAD

**Issue by geoffwright240** [numpy/numpy-financial#39]
For the following set of cash flows, I would expect the IRR to return 12%. 

`cf = np.array([-217500.0, -217500.0, 108466.80462450592, 101129.96439328062, 93793.12416205535, 86456.28393083003, 79119.44369960476, 71782.60346837944, 64445.76323715414, 57108.92300592884, 49772.08277470355, 42435.24254347826, 35098.40231225296, 27761.56208102766, 20424.721849802358, 13087.88161857707, 5751.041387351768, -1585.7988438735192, -8922.639075098821, -16259.479306324123, -23596.31953754941, -30933.159768774713, -38270.0, -45606.8402312253, -52943.680462450604, -60280.520693675906, -67617.36092490121])
`

However, from the code, we have the following choice being made:
`   # NPV(rate) = 0 can have more than one solution so we return
    # only the solution closest to zero.`
    `rate = 1/res - 1`
    `print(rate)`
`[-0.01809679  0.12 ]`

As you can see, 12% is one of the solutions but it is discarded. 
This leads me to question whether choosing the solution that is closest to zero is indeed the right choice here and would appreciate the group's feedback.

**Comment by geoffwright240** [comment]
I see that PR https://github.com/numpy/numpy-financial/pull/32 will solve this issue.

**Comment by geoffwright240** [comment]
I came across an interesting paper that discusses the problem of which root to choose when evaluating an IRR equation.

http://www.utstat.utoronto.ca/~alexander/irr-soln.pdf

The authors argue that choosing the largest root is generally the correct 'interpretation' for what most users are expecting from an IRR equation. While I fully acknowledge that all roots are correct solutions to the mathematical problem, I believe it probably makes sense to adopt the Law of the Largest Root when no guess is given.

The current code simply chooses the root that is closest to zero. This is not incorrect mathematically but it appears arbitrary compared to the approach spelled out in the attached reference. (Does anyone know the reasoning underlying the current root selection choice?)
[irr-soln (1).pdf](https://github.com/numpy/numpy-financial/files/6447452/irr-soln.1.pdf)

**Comment by Kai-Striega** [comment]
@geoffwright240 I'm going to be doing some maintenance work on numpy-financial and I think this will be a good fix. Thankyou for contributing that paper, I agree that it should be the smallest positive root. Incidentally, this seems to have been the original intention of the code too:

 https://github.com/numpy/numpy-financial/blob/e624d268dcf00fffd05580726819ade0edc3e4ff/numpy_financial/_financial.py#L770-L771

I don't agree with taking an initial guess as the result. I'm going to get a bit of maintenance stuff done and then I'll get back to this.

**Comment by Kai-Striega** [comment]
closed by #43

**Comment by geoffwright240** [comment]
Thanks Kai!

**Comment by Kai-Striega** [comment]
Thank you for taking the time to research this.

> From the Microsoft page there is sparse detail - they start with the guess and iterate - what ever that means.

That means they are using some kind of numerical algorithm that takes steps towards the correct solution. If you're interested in reading up on them it would probably be something similar to the [Newton-Raphson](https://en.wikipedia.org/wiki/Newton%27s_method) method if you'd like to read up on it.

> LibreOffice documentation seems to suggest that it mirrors Excel (down to the same assumed initial guess = 0.1 / 10%).

They do look similar, what I'm worried about is the behavior that's not documented (e.g. what is the stepsize for iterations)

> I think the current solution isn't actually iterative is it? It assumes that the solution can be calculated in closed form from the roots - and selecting one is essentially a crap shoot.

IRR finds the eigenvalues of the [Companion matrix](https://en.wikipedia.org/wiki/Companion_matrix), which correspond to the roots of the polynomial equation. This returns **all** the roots (which is redundant) and slow (see #40) and leaves ambiguity in how to select the correct root.

> So I think you are right, picking the solution that is closest to the given guess is not necessarily going to give a solution that matches Excel 100% of the time. Short of reimplementing to use the iterative approach though, I think it's probably the best idea (that I can think of).

I'm starting to think that reimplementing IRR with an iterative approach would be the best way of doing it. Would you be interested in doing it? If you are, here is a good paper to get started:


- Pascual, Nerio & Sison, Ariel & Gerardo, Bobby & Medina, Ruji. (2018). Calculating Internal Rate of Return (IRR) in Practice using Improved Newton-Raphson Algorithm. Philippine Computing Journal. 13. 17-21.  https://www.researchgate.net/publication/338749495_Calculating_Internal_Rate_of_Return_IRR_in_Practice_using_Improved_Newton-Raphson_Algorithm

**Comment by jamiecook** [comment]
@Kai-Striega  - I would be quite interested in this actually. I just haven't had a lot of time recently - but could pick it up now. I'll look into doing up an initial impl for discussion.

**Comment by jamiecook** [comment]
Oh - you've already picked it up in #47
