### ISSUE TITLE
Extremely slow to calculate IRR 

### ISSUE THREAD

**Issue by UGuntupalli** [numpy/numpy-financial#40]
I just came across this package as I realized that ```np.irr()``` has been migrated over into this package. As I tried to get familiar with it, I was just stumped with the amount of time it takes to calculate IRR. If this package is being maintained, I would really like to know why it takes this long and if there are any recommended alternatives. Here is a quick example I compiled: 

```python
import pandas as pd
import numpy as np
import numpy_financial as npf
from time import time


# Generate some example data
t = pd.date_range('2022-01-01', '2037-01-01', freq='D')

cash_flows = np.random.randint(10000, size=len(t)-1)
cash_flows = np.insert(cash_flows, 0, -10000)

# Calculate IRR
start_timer = time()
npf.irr(cash_flows, guess)
stop_timer = time()
print(f"""Time taken to calculate IRR over 30 years of daily data: {round((stop_timer-start_timer)/60, 2)}""")
```

It took over a minute to calculate IRR for 30 years of daily data. I am wondering if the lack of an initial guess is slowing this down and if that needs to be added ?

**Comment by Kai-Striega** [comment]
Hi I'm going to be doing some work on tidying up numpy-financial. Please note that I haven't yet done any profiling, so take all this as (educated) guess work.

Looking at the IRR function it uses an internal function called ``_roots`` to find the values for r where ``NPV(cashflows, r) == 0``. This function is defined here: https://github.com/numpy/numpy-financial/blob/e3c2a4eccd1f44082597ace0550eb3daf20156fd/numpy_financial/_financial.py#L687-L700

I suspect that constructing and finding the eigenvalues of such a large matrix is where the performance is going downhill and that implementing a more specialized solution for large inputs is the better way to go. I'm not sure if an initial guess will help with the current algorithm and, again, I haven't actually profiled it yet. 

P.S. 2022 to 2037 is 15 years, but that just adds to your point of it being to slow for large date ranges.

**Comment by Kai-Striega** [comment]
I've done some profiling and (by far!) the most time is spent trying to calculate the eigenvalues of that matrix. For a 5 years of daily data it takes approximately 7.658 of 7.678 seconds according to asv. I'll need to think about whether there is a good way to optimize this for large cashflows.

**Comment by UGuntupalli** [comment]
@Kai-Striega, 

Sorry for the late response. I have started using pyxirr package instead and have found that it is able to meet the needs well. Perhaps you can take a look at it ?

**Comment by Kai-Striega** [comment]
> Sorry for the late response.

Thanks for volunteering your time.

> I have started using pyxirr package instead and have found that it is able to meet the needs well. Perhaps you can take a look at it ?

Thank you for the recommendation. I've had a look at it and it implements a numerical solve similar to that in #47. Note that this is a prototype and I still need some fixes. At least this reinforces the fact that we are going down the correct route.
