### ISSUE TITLE
IRR incorrect with when number of cashflows exceed 9 and final cashflow is negative

### ISSUE THREAD

**Issue by c-stephenson** [numpy/numpy-financial#44]
Steps to re-produce:
```
irr = npf.irr([-1678.87,771.96,1814.05,3520.30,3552.95,3584.99,-1])
print(f"Working IRR : {irr}")

irr = npf.irr([-1678.87,771.96,1814.05,3520.30,3552.95,3584.99,4789.91,-1])
print(f"Not Working IRR : {irr}")
```
Output:
```
Working IRR : 0.9688775470209179
Not Working IRR : -0.9997912604283283
```

**Comment by Kai-Striega** [comment]
Which version of numpy_financial are you using? You can get the version by entering:

```python
import numpy_financial as npf
npf.__version__
```

I've recently made some changes to `irr`. Before it would prioritize the smallest rate. `irr` now prioritizes the lowest positive rate, only returning a negative rate if no positive rate exists. On the master branch:
```python
import numpy_financial as npf
npf.__version__
'1.1.0.dev0'
npf.irr([-1678.87,771.96,1814.05,3520.30,3552.95,3584.99,-1])
0.9688775470209179
npf.irr([-1678.87,771.96,1814.05,3520.30,3552.95,3584.99,4789.91,-1])
1.004269848720547
```
does this look more correct to you?

**Comment by c-stephenson** [comment]
Hi,
Thanks for the prompt response. I'm using the latest pulled down from pypi, version **1.0.0**

1.0.0.dev0 looks like it's fixing this problem :)

I will pull this latest version down from your master.

Thank you,
C.

**Comment by Kai-Striega** [comment]
>Thanks for the prompt response.
You're welcome ;)

> 1.0.0.dev0 looks like it's fixing this problem :)
> I will pull this latest version down from your master.

I'm glad it's resolved so easily. If there are any unexpected results could you please open another issue so I find out about them before they get included in the final release?

I'm also going to add your example as a regression test.
