### ISSUE TITLE
npf.rate() returns list of all nans where only one input PV/FV pair is problematic

### ISSUE THREAD

**Issue by tylerdegroff** [numpy/numpy-financial#48]
Hello,

Today I noticed that where a list of present values and a list of future values are used as input to `npf.rate()`, _each_ element in the list returned is `nan` if only just _one_ present/future value combination exhibits the same sign. Is this behavior intentional? I would have expected only that particular problematic pair to have returned `nan`, as the other pairs' results remain valid and calculable.

As you can see by the reproducible example below, all you need to do to resolve this case is drop the last element from each list and the preceding elements (all of which exhibit opposing signs) calculate as expected. Leave the last elements in place, and you get back a list of all `nan`.
 
Thanks!
-Tyler

```
import numpy_financial as npf

pv = [-593.06, -4725.38, -662.05, -428.78, -13.65]
fv = [214.07, 4509.97, 224.11, 686.29, -329.67]

print(npf.rate(2, 0, pv, fv))
```
[nan nan nan nan nan]
```
print(npf.rate(2, 0, pv[0:-1], fv[0:-1]))
```
[-0.39920185 -0.02305873 -0.41818459 0.26513414]

**Comment by Kai-Striega** [comment]
Hi Tyler,

I've had a look around the code and it looks like it is done intentionally. Whether this should be the desired behavior is another question. I believe that in your example a better result would be the rate where it can be found and `nan` where it can't. If you agree with this I'd be happy to implement an update.

Thank you for raising this issue.

Kai
