### ISSUE TITLE
Slow NPV calculations for monte carlo simulation purposes

### ISSUE THREAD

**Issue by jowahlin** [numpy/numpy-financial#52]
When using a large number of monte carlo simulations (~1e6 or more) for uncertainty calculations on NPV, the present implementation of Numpy-financial NPV is very slow. We suggest a new implementation of the NPV function , which allows calculation of serveral projects simultaneously, and is approximately 200 times faster than the current version for 1e6 simulations for a cash-flow of length 10.

In cases where the number of entries in the cash-flow is significantly higher than the number of projects to be calculated, the old implementation will be faster. To solve this, we suggest an adaptive approach which chooses method based on the input dimensions of the 'values' array.

Example code:
```
import numpy_financial as npf
import numpy as np
import time

def faster_npv(rate: float, values: list):
    """ A faster way to calculate NPV for several projects based 
    on numpy arrays. """
    discounted_values = []
    for i in range(np.shape(values)[0]):
        discounted_values.append(values[i] / (1 + rate) ** i)
    return np.sum(discounted_values, axis=0)

rate=0.05
no_simulations = int(1e6)

capex = np.random.normal(loc=10e5, scale = 10e3, size=no_simulations)
lifetime = 10 #years

opex = []
for yr in range(lifetime):
    opex.append(np.random.normal(loc=10e4, scale= 10e2,size=no_simulations))

start_time=time.time()
all_npv=np.nan*np.ones_like(capex)
for i in range(no_simulations):
    values = [capex[i]]+[op[i] for op in opex]
    all_npv[i]=npf.npv(rate, values)
print(f"Standard NPF calculations took {time.time()-start_time} s.")

start_time=time.time()
values=[capex]+opex
faster_npv(rate,values )
print(f"Faster NPV calculations took {time.time()-start_time} s.")
```

**Comment by Kai-Striega** [comment]
Hi @jowahlin thank you for taking the time to raise an issue. Sorry about the delayed response. I've refactored the code (see at end) to avoid creating ``values`` inside the for loop and removed some loops in favor of list comps. I agree the current implementation is very slow and that your implementation is significantly faster. Having two separate implementations could be a good idea - I haven't looked into it yet. Another option that I have been considering is adding Numba as a dependency.

```python
import numpy_financial as npf
import numpy as np
import time

from numpy.testing import assert_allclose


def faster_npv(rate: float, values: list):
    """ A faster way to calculate NPV for several projects based
    on numpy arrays. """
    discounted_values = []
    for i in range(np.shape(values)[0]):
        discounted_values.append(values[i] / (1 + rate) ** i)
    return np.sum(discounted_values, axis=0)


rate = 0.05
no_simulations = int(1e6)
lifetime = 10  # years

capex = np.random.normal(loc=10e5, scale=10e3, size=(1, no_simulations))
opex = np.random.normal(loc=10e4, scale=10e2, size=(lifetime, no_simulations))
values = np.concatenate((capex, opex))

start_time = time.time()
all_npv_slow = [npf.npv(rate, values[:, i]) for i in range(no_simulations)]
print(f"Standard NPF calculations took {time.time() - start_time}s.")

start_time = time.time()
all_npv_fast = faster_npv(rate, values)
print(f"Faster NPV calculations took {time.time() - start_time}s.")

assert_allclose(all_npv_fast, all_npv_slow)
```

**Comment by jowahlin** [comment]
Hi,

Thanks for your reply, and your improvements. I've, temporarily, disregarded them (sorry!) as I restructured the input format into something that felt more intuitive. Instead of arrays of capex and opex:es, we structure the input as a list of simulated projects, like this:
``` 
project_simulation_1=[-5000, 200, 300,100,100]
project_simulation_2=[-2000, 200, 300,300,300]
project_simulation_3=[-4000, 200, 300,200,200]
project_simulation_4=[-1000, 100, 100,100,100]

values = [project_simulation_1, 
               project_simulation_2, 
               project_simulation_3, 
               project_simulation_4]

npv = faster_npv(rate, values)

```
Don't know what you think, it does not really matter for the calculations.

Disliking my two implementations-idea, I looked a bit closer at the problem and realized that it can be done much easier, with the same piece of code. This version is significantly faster for high number of simulations and moderate number of timesteps (<100), or moderate number of simulations and high number of timesteps. For large number of simulations and large number of timesteps (~300), the standard implementation is approximately 25% faster. 

``` 
def faster_npv(rate: float, values: list):
    """ A faster way to calculate NPV for several projects based
    on numpy arrays. """
    values=np.atleast_2d(values)
    timestep_array = np.tile(np.arange(0, values.shape[1]),(values.shape[0],1))
    npv = (values / (1+rate)**timestep_array).sum(axis=1)
    try:
        # If size of array is one, return scalar
        return npv.item()
    except ValueError:
        # Otherwise return entire array
        return npv


rate = 0.05
no_simulations = int(1e6)
lifetime = 10  # years

capex=np.random.normal(loc=1000, scale=100, size=no_simulations)
opex=np.random.normal(loc=100, scale=10, size=no_simulations)
values = np.array([capex]+[opex]*lifetime).transpose()

start_time = time.time()
all_npv_slow = [npf.npv(rate, values[i]) for i in range(no_simulations)]
print(f"Standard NPF calculations took {time.time() - start_time}s.")

start_time = time.time()
all_npv_fast = faster_npv(rate, values)
print(f"Faster NPV calculations took {time.time() - start_time}s.")

assert_allclose(all_npv_fast, all_npv_slow)
```

Just some thoughts :)

**Comment by Kai-Striega** [comment]
Overall I'm a fan of what you are doing here. 

I'm not a fan of using ``np.tile``, the reason being that it constructs an additional array in memory that, in this case, is extremely large and can lead to problems. On my systems this occurs for ``lifetime`` ~ 440. It is also significantly slower for large lifetimes, on my machine I get the following output for ``lifetime = 430``:
```
Standard NPF calculations took 15.113217115402222s.
Faster NPV calculations took 25.28099226951599s.
```
