### ISSUE TITLE
import numpy_financial as npf

### ISSUE THREAD

**Issue by ahermano0** [numpy/numpy-financial#53]
hello i  am trying to assign import numpy_financial as npf  on jupiter note but i have some errors :
NameError:  name 'numpy_financial' is not defined.
i am sorry i am new to python .

**Comment by Kai-Striega** [comment]
Hi @ahermano0 I'm going to try and help you out but first I need to figure out exactly what is wrong. Could you show me *exactly* the code that you are trying to run?

**Comment by Kai-Striega** [comment]
I'm going to close this issue as @ahermano0 hasn't responded with any further information
