### ISSUE TITLE
TST: Replace `assert_almost_equal` checks with `assert_allclose` in test suite

### ISSUE THREAD

**Issue by Kai-Striega** [numpy/numpy-financial#66]
`assert_almost_equal` is no longer the recommended way of checking for two numbers that are close to one another due to the inconsistencies in how floating point numbers are handled.  It is recommended to use one of `assert_allclose`, `assert_array_almost_equal_nulp` or `assert_array_max_ulp` instead of this function for more consistent floating point               comparisons.

This issue is to replace `assert_almost_equal` with the appropriate check

**Comment by ArCh12312** [comment]
Hey!
I would like to take up this issue. 
Could you please assign it to me?

**Comment by Kai-Striega** [comment]
Closed via #97, closing this issue.
