### ISSUE TITLE
TST/CI: Automatically test documentation when it is built

### ISSUE THREAD

**Issue by Kai-Striega** [numpy/numpy-financial#73]
### Proposed new feature or change:

The CI pipeline should automatically test the code examples in the documentation when it is being built. This will ensure that our documentation remains current.

**Comment by MashyBasker** [comment]
Hi, I'd like to work on this issue.

To my understanding, we can install `doctest` and use it on the `numpy_financial/_financial.py/financial.py` file to test against the examples in the docstrings.

But I cannot understand if I should install `doctest`  in the `publish_docs_to_pages.ym`l or the `pythonpackage.yml` workflow. Please correct me if I have made any mistake in my understanding.

Thanks.
