### ISSUE TITLE
DOC: Test examples in doctstrings fail

### ISSUE THREAD

**Issue by MashyBasker** [numpy/numpy-financial#95]
### Issue with current documentation:

The test examples provided in the docstrings of `numpy_financial/_financial.py` mostly fail.

![image](https://github.com/numpy/numpy-financial/assets/84385565/8e440b15-50b7-4bf5-9973-ee60323a966c)

**Comment by Kai-Striega** [comment]
Thanks for raising the issue — that's a bit of a worry!

Are these mostly due to floating point imprecision? E.g. in the example above the array looks _almost_ equal except for the `# may vary` comment.

**Comment by MashyBasker** [comment]
I think these might get resolved if `assert_allclose` is used in the tests instead of `assert_almost_equal`.
As mentioned in [issue#66](https://github.com/numpy/numpy-financial/issues/66)
