### ISSUE TITLE
BUG: There may exist multplit roots in the solution of IRR function

### ISSUE THREAD

**Issue by yatshunlee** [numpy/numpy-financial#98]
### Describe the issue:

This was what I encountered:
![image](https://github.com/numpy/numpy-financial/assets/69416199/24b4ec6b-a662-46ce-ab31-2678f5eed1bf)

What I got in Excel:
![image](https://github.com/numpy/numpy-financial/assets/69416199/d7705484-b267-4b8c-bf95-d59197802e17)

### Reproduce the code example:

```python
import numpy_financial as npf
print(npf.irr([-10000]+[327.24625]*16))
```

### Error message:

```shell
NA
```

### Runtime information:

NA

### Context for the issue:

There may exist multplit roots in the solution of IRR function so that the `irr()` may give an incorrect result.

**Comment by Kai-Striega** [comment]
Hello @yatshunlee: firstly my apologies for taking so long to reply, I was on holiday over Christmas/New Years and didn't check my GitHub. I'm back and should be quicker to respond from now on. 

What version of NumPy-Financial are you using? 

`irr` has given us a lot of problems, and we are well aware that there is (usually) more than one solution. In the development version, it uses a completely different solver based on Newton's method and a `guess` parameter. `guess` can be changed to influence the solution from `irr`.  Using a guess of 0.1 (10%) will give the same solution as Excel:

```python
>>> import numpy_financial as npf
>>> npf.__version__
'1.1.0.dev0'
>>> npf.irr([-10000]+[327.24625]*16)
-1.7781470715009497
>>> npf.irr([-10000]+[327.24625]*16, guess=0.1)
-0.06765411344912187
```

I'm currently working on a grant to upgrade NumPy-Financial, after which I plan on releasing a 2.0 release which will contain this feature.

**Comment by yatshunlee** [comment]
By referring to your `iir` function at v1.0, I have created a relatively stable (to me) version of `iir` which **doesn't require me to give an inital guess**. I can help to contribute or try to give an alternative way to solve. May I create a pull request so that you can take a look and see if my edit also works for you so that you don't have to spend extra time to solve it?

**Comment by Kai-Striega** [comment]
You're welcome to submit a PR and I'll review it. 

However I think it's quite unlikely that we will move from the iterative solver for the reason that it is both simpler and faster.
